sonar.projectKey=videojuego-js
sonar.projectName=Videojuego JS
sonar.host.url=http://localhost:9000

sonar.sources=js,css,index.html

sonar.exclusions=assets/**,node_modules/**,dist/**,build/**,coverage/**,.scannerwork/**

sonar.sourceEncoding=UTF-8